"""PR 준비/생성. 기본은 **미리보기**(명령만 출력). --execute 일 때만 브랜치 push + PR 생성.

- 게이트 결정이 CREATE_PR_AUTO / CREATE_PR_APPROVAL 인 run 만 PR 로 만든다 (BLOCK/HOLD/REPORT_ONLY 는 거부).
- 병합(merge)과 apply 는 어떤 경우에도 자동으로 하지 않는다.
- GitHub API 는 urllib 로 호출하며 토큰은 환경변수 GITHUB_TOKEN 에서만 읽는다.
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List, Optional

from ..config import Settings
from .runner import run, which


def _repo_slug(remote_url: str) -> Optional[str]:
    m = re.search(r"github\.com[:/]([^/]+)/([^/.]+)(\.git)?/?$", remote_url.strip())
    return f"{m.group(1)}/{m.group(2)}" if m else None


def prepare_pr(settings: Settings, run_id: str, execute: bool = False, base_branch: str = "main",
               remote: str = "origin", draft: bool = False) -> int:
    run_dir = settings.path(settings.data_dir) / run_id
    run_json = run_dir / "run.json"
    if not run_json.exists():
        print(f"run record not found: {run_dir}")
        return 2
    run_info = json.loads(run_json.read_text(encoding="utf-8"))
    gate = (run_info.get("gate") or {})
    action = gate.get("action")
    if action not in ("CREATE_PR_AUTO", "CREATE_PR_APPROVAL"):
        print(f"refusing to create a PR: gate action is {action!r} (only CREATE_PR_AUTO / CREATE_PR_APPROVAL may become PRs)")
        return 3
    attempt = int(run_info.get("final_attempt") or 1)
    files_dir = run_dir / "candidates" / f"{attempt:02d}" / "files"
    target_dir = run_info.get("target_dir")
    scenario = run_info.get("scenario_id", "scenario")
    body_path = run_dir / "pr_body.md"
    files = sorted(p for p in files_dir.rglob("*") if p.is_file())
    if not files:
        print("no candidate files in the run record")
        return 2
    branch = f"iacpatch/{scenario}-{run_id}".replace(" ", "-")
    title = f"[iacpatch] {scenario}: {run_info.get('target_finding', {}).get('rule_id', '')} on {run_info.get('target_finding', {}).get('resource', '')}"
    if action == "CREATE_PR_APPROVAL":
        title = "[approval required] " + title
    repo_root = Path(settings.repo_root)
    commands: List[str] = [
        f"cd {repo_root}",
        f"git fetch {remote} {base_branch}",
        f"git checkout -b {branch} {remote}/{base_branch}",
    ]
    for p in files:
        rel = p.relative_to(files_dir)
        commands.append(f"cp {p} {repo_root / target_dir / rel}")
    commands += [
        f"git add {target_dir}",
        f"git commit -F {run_dir / 'commit_message.txt'}",
        f"git push -u {remote} {branch}",
        f"gh pr create --base {base_branch} --head {branch} --title \"{title}\" --body-file {body_path}" + (" --draft" if draft else ""),
    ]
    commit_msg = (f"{title}\n\nGenerated by iacpatch run {run_id} (generator={run_info.get('generator')}, gate={action}).\n"
                  f"Verification: {(run_info.get('validity') or {}).get('summary', '')}\n"
                  "This commit was produced by an automated pipeline; a human must review and approve before merge and before terraform apply.\n")
    (run_dir / "commit_message.txt").write_text(commit_msg, encoding="utf-8")
    (run_dir / "pr_commands.sh").write_text("#!/usr/bin/env bash\nset -euo pipefail\n" + "\n".join(commands) + "\n", encoding="utf-8")
    print(f"PR preparation for run {run_id} (gate={action})")
    print(f"  branch : {branch}")
    print(f"  title  : {title}")
    print(f"  body   : {body_path}")
    print(f"  script : {run_dir / 'pr_commands.sh'}")
    if not execute:
        print("preview only. Review pr_body.md, then either run the script above yourself or re-run with --execute.")
        return 0

    # --- execute -------------------------------------------------------------
    if which("git") is None:
        print("git not found")
        return 2
    st = run(["git", "status", "--porcelain", "--", target_dir], cwd=str(repo_root))
    if st.stdout.strip():
        print(f"working tree has uncommitted changes under {target_dir}; refusing to continue")
        return 4
    cur = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=str(repo_root)).stdout.strip()
    steps = [["git", "fetch", remote, base_branch], ["git", "checkout", "-b", branch, f"{remote}/{base_branch}"]]
    for argv in steps:
        r = run(argv, cwd=str(repo_root))
        if not r.ok:
            print(f"{' '.join(argv)} failed: {r.stderr.strip()}")
            return 5
    for p in files:
        rel = p.relative_to(files_dir)
        dst = repo_root / target_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(p.read_text(encoding="utf-8"), encoding="utf-8")
    for argv in (["git", "add", target_dir], ["git", "commit", "-F", str(run_dir / "commit_message.txt")], ["git", "push", "-u", remote, branch]):
        r = run(argv, cwd=str(repo_root))
        if not r.ok:
            print(f"{' '.join(argv)} failed: {r.stderr.strip()}")
            run(["git", "checkout", cur], cwd=str(repo_root))
            return 5
    remote_url = run(["git", "remote", "get-url", remote], cwd=str(repo_root)).stdout.strip()
    slug = _repo_slug(remote_url)
    token = os.environ.get("GITHUB_TOKEN")
    if not slug or not token:
        print(f"branch pushed. PR not created automatically ({'no GITHUB_TOKEN' if not token else 'remote is not github.com'}). Run: {commands[-1]}")
        return 0
    body = {"title": title, "head": branch, "base": base_branch, "body": body_path.read_text(encoding="utf-8"), "draft": draft}
    req = urllib.request.Request(f"https://api.github.com/repos/{slug}/pulls", data=json.dumps(body).encode("utf-8"), method="POST")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            d = json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        print(f"PR creation failed: HTTP {e.code} {e.read().decode('utf-8', 'replace')[:300]}")
        return 6
    (run_dir / "pr.json").write_text(json.dumps({"number": d.get("number"), "url": d.get("html_url"), "branch": branch}, indent=2), encoding="utf-8")
    print(f"PR created: {d.get('html_url')}  (merge and apply remain manual)")
    return 0
